# Generated by Django 4.1 on 2022-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
