# Generated by Django 4.1 on 2022-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_monthdata_yeardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('condition', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
