# Generated by Django 4.1 on 2022-12-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_bridge_inventorydata_alter_daydata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridge',
            old_name='type',
            new_name='bridge_type',
        ),
    ]
