# Generated by Django 4.1 on 2022-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_type_bridge_bridge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydata',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
