# Generated by Django 4.1 on 2022-12-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_inventorydata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydata',
            name='incharge',
        ),
    ]
